### ISSUE TITLE
Import of adventure fails because of missing property

### ISSUE THREAD

**Issue by JanSchattling** [dmarcuse/fvtt-adventure-bundler#11]
Hi.
I exported an scenario including npcs, music and journal entry.
When trying to import it, I get the error message "Cannot read properties of null (reading '_tombstone')"
I already found out that this is probably a class and not a real tombstone but that didn't help much.
https://foundryvtt.com/api/classes/foundry.data.TombstoneData.html

I attached my zip file of the "adventure", maybe that can help?

[Seaside Tavern.zip](https://github.com/dmarcuse/fvtt-adventure-bundler/files/12170835/Seaside.Tavern.zip)

**Comment by dmarcuse** [comment]
Which game system does this use?

**Comment by dmarcuse** [comment]
Digging into the data, it looks like this was using the D&D 5e system. I'm not sure exactly what caused it, but the issue seems to be that the token for the Bard actor has some bad data that's causing validation issues when importing. Could you try the following steps and see if it's still broken?

1. Remove and replace the Bard token on the scene
2. Rebuild the adventure document
3. Export the bundle, then try importing it again

**Comment by JanSchattling** [comment]
Hi.
Yes, 5e was correct and it seems something with the data of this one NPC really was broken.
When I followed your instructions it all worked perfectly.
Thank you very much, your amazing module makes my adventure preparations so much easier.
